---
- name: "Copy backend files to the new server."
  copy:
    src: ~/project/backend
    dest: ~/project

- name: "Extract Files and starting the app"
  shell: |
    cd ~/project
    tar -xzvf artifact.tar.gz -C backend
    cd backend/
    npm install
    pm2 stop default
    pm2 start npm -- start