---
- name: "Copy archived backend files to the new server."
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "Extract Files and starting the app"
  shell: |
    cd ~/
    tar -xzvf artifact.tar.gz -C backend
    rm artifact.tar.gz
    cd backend/
    npm install
    pm2 stop default
    pm2 start npm -- start